### ISSUE TITLE
TcpConnectionLink error

### ISSUE THREAD

**Issue by rhayman** [open-ephys-plugins/neuropixels-3a#3]
Using a recent copy of the pre-compiled binaries for Neuropixels and dropping the NeuropixPlugin3a plugin into the signal chain results in the following error:

```
Item dropped at insertion point 0
Creating from description...
Sources::Neuropix-3a (2-2)
TcpConnectionLink
Failure with error code 4
  Adding node to graph with ID number 100
```

Note that I can connect to the probe using SpikeGLX.

Any help massively appreciated as I have plugins I've written for OE that I'd really like to use with the probes

**Comment by jsiegle** [comment]
Error code 4 is `WRONG_HW_SW_VERSION`...do you know what firmware version you have installed on your Xilinx board?

**Comment by rhayman** [comment]
Fairly certain it's 5.2

I'm away from the lab for the evening but can confirm in the morning

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jsiegle** [comment]
SpikeGLX is compiled against imec's API v4.3, which works with firmware v4.2. The Open Ephys Neuropix-3a plugin is compiled against API v5.5, which works with firmware v5.1 or 5.2.

So the error would make perfect sense if you're actually using firmware v4.2. Let me know what you find!

If you'd like to use SpikeGLX with the same hardware, then we can compile a version of Open Ephys that's compatible with the older API version. We are happy to do this, but we'd have to switch to a 32-bit application, because the older libraries are 32-bit only.

The other solution would be for you to upload a more recent bitfile (v5.1 or v5.2), which will work with the pre-compiled binaries. We can send these to you if you don't have access already.

**Comment by frikyng** [comment]
Hi, I have the exact same issue when we want to use NP phase 3a probes with open ephys. I am running firmware version 4.2 as distributed with the probes when they were bought. Is there a way to get a compiled version of open ephys?

**Comment by jsiegle** [comment]
If at all possible, we'd recommend upgrading your firmware to version 5.1 (available [here](https://www.dropbox.com/s/rj0w979wjjxlxxr/neuropix_basestation.mcs?dl=0)). That will allow you to run the standard version of the GUI, and easily stay up-to-date with future upgrades.

But if that won't work (e.g., if you want to use SpikeGLX with the same board), then @medengineer can generate a 32-bit version of the GUI for you.
